// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";
import {RuleV2Lib} from "../src/lib/RuleV2Lib.sol";

/// @title RuleVectorsTest — differential parity between Solidity and TypeScript engines.
/// @notice Replays 500 seeded vectors generated by server/scripts/gen-vectors.ts.
///         The TS engine wrote `expected`; this suite asserts the Solidity engine
///         returns the identical reason for every vector. Drift in either fails CI.
contract RuleVectorsTest is Test {
    struct JsonHolder {
        string country;
        string cvRecordId;
        bool exists;
        uint256 expiry;
        string group;
        uint256 status;
        string subGroup;
        uint256 subTier;
        uint256 tier;
    }

    struct JsonRule {
        bool active;
        string[] countries;
        string group;
        bool isBlackList;
        uint256 minSubTier;
        uint256 minTier;
        string subGroup;
    }

    struct JsonVector {
        uint256 expected;
        JsonHolder holder;
        uint256 now_;
        JsonRule rule;
    }

    function _b2(string memory s) internal pure returns (bytes2) {
        bytes memory b = bytes(s);
        if (b.length == 0) return bytes2(0);
        return bytes2(bytes.concat(b[0], b.length > 1 ? b[1] : bytes1(0)));
    }

    function test_differentialParityWithTypeScript() public view {
        string memory raw = vm.readFile("test/vectors.json");
        // Vectors are serialized in generation order; keys within objects are alphabetized by forge's parser.
        uint256 n = 500;
        uint256 mismatches;
        for (uint256 i; i < n; ++i) {
            string memory p = string.concat("[", vm.toString(i), "]");

            RuleV2Lib.Holder memory h;
            h.cvRecordId = bytes32(i + 1);
            h.tier = uint8(vm.parseJsonUint(raw, string.concat(p, ".holder.tier")));
            h.subTier = uint8(vm.parseJsonUint(raw, string.concat(p, ".holder.subTier")));
            h.group = _b2(vm.parseJsonString(raw, string.concat(p, ".holder.group")));
            h.subGroup = _b2(vm.parseJsonString(raw, string.concat(p, ".holder.subGroup")));
            h.country = _b2(vm.parseJsonString(raw, string.concat(p, ".holder.country")));
            h.status = uint8(vm.parseJsonUint(raw, string.concat(p, ".holder.status")));
            h.expiry = uint64(vm.parseJsonUint(raw, string.concat(p, ".holder.expiry")));
            h.exists = vm.parseJsonBool(raw, string.concat(p, ".holder.exists"));

            RuleV2Lib.Rule memory r;
            r.group = _b2(vm.parseJsonString(raw, string.concat(p, ".rule.group")));
            r.subGroup = _b2(vm.parseJsonString(raw, string.concat(p, ".rule.subGroup")));
            r.minTier = uint8(vm.parseJsonUint(raw, string.concat(p, ".rule.minTier")));
            r.minSubTier = uint8(vm.parseJsonUint(raw, string.concat(p, ".rule.minSubTier")));
            string[] memory cs = vm.parseJsonStringArray(raw, string.concat(p, ".rule.countries"));
            r.countries = new bytes2[](cs.length);
            for (uint256 c; c < cs.length; ++c) {
                r.countries[c] = _b2(cs[c]);
            }
            r.isBlackList = vm.parseJsonBool(raw, string.concat(p, ".rule.isBlackList"));
            r.active = vm.parseJsonBool(raw, string.concat(p, ".rule.active"));

            uint256 nowTs = vm.parseJsonUint(raw, string.concat(p, ".now"));
            uint256 expected = vm.parseJsonUint(raw, string.concat(p, ".expected"));

            uint256 got = uint256(RuleV2Lib.evaluate(h, r, nowTs));
            if (got != expected) {
                ++mismatches;
                console2.log("vector", i);
                console2.log("expected", expected);
                console2.log("got", got);
            }
        }
        assertEq(mismatches, 0, "solidity/typescript rule engines disagree");
    }
}
